name: Run Greet Action

on:
  push:
    branches:
      - main

jobs:
  greet-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run custom greet action
        uses: ./greet-action
        with:
          name: "Raju"